parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
#            - '../src/Entity/'
            - '../src/Kernel.php'

    App\View\Controller\Product\:
        resource: '%kernel.project_dir%/src/View/Controller/Product'
        tags: [ 'controller.service_arguments' ]

    App\Infrastructure\Twig\Extension\DateExtension:
        tags: [ 'twig.extension' ]

    App\Infrastructure\Twig\Extension\EnumExtension:
        tags: [ 'twig.extension' ]